### ISSUE TITLE
connection to pleroma

### ISSUE THREAD

**Issue by wildflypower** [moko256/twitlatte#62]
cannot connect any instance of pleroma

**Comment by wildflypower** [comment]
``2019-08-23 09:34:47.116 29717-29717/com.github.moko256.twitlatte.debug I/Timeline: Timeline: Activity_launch_request time:28798048 intent:Intent { act=android.intent.action.VIEW dat=https://******.com/... (has extras) }
2019-08-23 09:35:09.585 29717-29717/com.github.moko256.twitlatte.debug W/System.err: java.lang.Exception: com.sys1yagi.mastodon4j.api.exception.Mastodon4jRequestException: com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: For input string: "9lypiXa9DAapAqWlQu"
2019-08-23 09:35:09.586 29717-29717/com.github.moko256.twitlatte.debug W/System.err:     at com.github.moko256.latte.client.mastodon.MastodonErrorConverterKt.executeAndConvertError(MastodonErrorConverter.kt:35)
2019-08-23 09:35:09.586 29717-29717/com.github.moko256.twitlatte.debug W/System.err:     at com.github.moko256.latte.client.mastodon.MastodonAuthApiClient.initializeToken(MastodonAuthApiClient.kt:87)
2019-08-23 09:35:09.586 29717-29717/com.github.moko256.twitlatte.debug W/System.err:     at com.github.moko256.twitlatte.model.impl.OAuthModelImpl$initToken$1.subscribe(OAuthModelImpl.kt:78)
2019-08-23 09:35:09.586 29717-29717/com.github.moko256.twitlatte.debug W/System.err:     at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39)
2019-08-23 09:35:09.586 29717-29717/com.github.moko256.twitlatte.debug W/System.err:     at io.reactivex.Single.subscribe(Single.java:3575)
2019-08-23 09:35:09.586 29717-29717/com.github.moko256.twitlatte.debug W/System.err:     at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
2019-08-23 09:35:09.586 29717-29717/com.github.moko256.twitlatte.debug W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
2019-08-23 09:35:09.587 29717-29717/com.github.moko256.twitlatte.debug W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
2019-08-23 09:35:09.587 29717-29717/com.github.moko256.twitlatte.debug W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
2019-08-23 09:35:09.587 29717-29717/com.github.moko256.twitlatte.debug W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2019-08-23 09:35:09.587 29717-29717/com.github.moko256.twitlatte.debug W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2019-08-23 09:35:09.587 29717-29717/com.github.moko256.twitlatte.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2019-08-23 09:35:09.587 29717-29717/com.github.moko256.twitlatte.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2019-08-23 09:35:09.587 29717-29717/com.github.moko256.twitlatte.debug W/System.err:     at java.lang.Thread.run(Thread.java:764)
2019-08-23 09:35:09.589 29717-29717/com.github.moko256.twitlatte.debug W/System.err: Caused by: com.sys1yagi.mastodon4j.api.exception.Mastodon4jRequestException: com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: For input string: "9lypiXa9DAapAqWlQu"
2019-08-23 09:35:09.589 29717-29717/com.github.moko256.twitlatte.debug W/System.err:     at com.sys1yagi.mastodon4j.MastodonRequest.execute(MastodonRequest.kt:60)
2019-08-23 09:35:09.589 29717-29717/com.github.moko256.twitlatte.debug W/System.err:     at com.github.moko256.latte.client.mastodon.MastodonErrorConverterKt.executeAndConvertError(MastodonErrorConverter.kt:33)
2019-08-23 09:35:09.589 29717-29717/com.github.moko256.twitlatte.debug W/System.err: 	... 13 more
2019-08-23 09:35:09.589 29717-29717/com.github.moko256.twitlatte.debug W/System.err: Caused by: com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: For input string: "9lypiXa9DAapAqWlQu"
2019-08-23 09:35:09.589 29717-29717/com.github.moko256.twitlatte.debug W/System.err:     at com.google.gson.internal.bind.TypeAdapters$11.read(TypeAdapters.java:306)
2019-08-23 09:35:09.590 29717-29717/com.github.moko256.twitlatte.debug W/System.err:     at com.google.gson.internal.bind.TypeAdapters$11.read(TypeAdapters.java:296)
2019-08-23 09:35:09.590 29717-29717/com.github.moko256.twitlatte.debug W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
2019-08-23 09:35:09.590 29717-29717/com.github.moko256.twitlatte.debug W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
2019-08-23 09:35:09.590 29717-29717/com.github.moko256.twitlatte.debug W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:927)
2019-08-23 09:35:09.590 29717-29717/com.github.moko256.twitlatte.debug W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:892)
2019-08-23 09:35:09.590 29717-29717/com.github.moko256.twitlatte.debug W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:841)
2019-08-23 09:35:09.590 29717-29717/com.github.moko256.twitlatte.debug W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:813)
2019-08-23 09:35:09.590 29717-29717/com.github.moko256.twitlatte.debug W/System.err:     at com.sys1yagi.mastodon4j.api.method.Accounts$getVerifyCredentials$2.invoke(Accounts.kt:32)
2019-08-23 09:35:09.591 29717-29717/com.github.moko256.twitlatte.debug W/System.err:     at com.sys1yagi.mastodon4j.api.method.Accounts$getVerifyCredentials$2.invoke(Accounts.kt:18)
2019-08-23 09:35:09.591 29717-29717/com.github.moko256.twitlatte.debug W/System.err:     at com.sys1yagi.mastodon4j.MastodonRequest.execute(MastodonRequest.kt:45)
2019-08-23 09:35:09.591 29717-29717/com.github.moko256.twitlatte.debug W/System.err: 	... 14 more
2019-08-23 09:35:09.609 29717-29717/com.github.moko256.twitlatte.debug W/System.err: Caused by: java.lang.NumberFormatException: For input string: "9lypiXa9DAapAqWlQu"
2019-08-23 09:35:09.610 29717-29717/com.github.moko256.twitlatte.debug W/System.err:     at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
2019-08-23 09:35:09.610 29717-29717/com.github.moko256.twitlatte.debug W/System.err:     at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
2019-08-23 09:35:09.610 29717-29717/com.github.moko256.twitlatte.debug W/System.err:     at java.lang.Double.parseDouble(Double.java:538)
2019-08-23 09:35:09.610 29717-29717/com.github.moko256.twitlatte.debug W/System.err:     at com.google.gson.stream.JsonReader.nextLong(JsonReader.java:964)
2019-08-23 09:35:09.610 29717-29717/com.github.moko256.twitlatte.debug W/System.err:     at com.google.gson.internal.bind.TypeAdapters$11.read(TypeAdapters.java:304)
2019-08-23 09:35:09.610 29717-29717/com.github.moko256.twitlatte.debug W/System.err: 	... 24 more
2019-08-23 09:35:09.642 29717-29717/com.github.moko256.twitlatte.debug I/Toast: Show toast from OpPackageName:com.github.moko256.twitlatte.debug, PackageName:com.github.moko256.twitlatte.debug

**Comment by moko256** [comment]
Sorry. Pleroma's api is a little different from Mastodon [at some points](https://mastodon.social/@Gargron/101489729849684852), so twitlatte doesn't work correctly. I'll fix it.
